"""initial_migration

Revision ID: 88beb69b6fdc
Revises: 
Create Date: 2025-04-04 14:02:27.180476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88beb69b6fdc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('match_id', sa.Integer(), nullable=False))
    op.drop_constraint('chats_trade_id_fkey', 'chats', type_='foreignkey')
    op.create_foreign_key(None, 'chats', 'matches', ['match_id'], ['match_id'])
    op.drop_column('chats', 'trade_id')
    op.add_column('matches', sa.Column('trade_request_time', sa.DateTime(), nullable=True))
    op.add_column('matches', sa.Column('ready_at', sa.DateTime(), nullable=True))
    op.drop_column('users', 'location')
    op.drop_column('users', 'profile_picture')
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('full_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('profile_picture', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('location', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('matches', 'ready_at')
    op.drop_column('matches', 'trade_request_time')
    op.add_column('chats', sa.Column('trade_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.create_foreign_key('chats_trade_id_fkey', 'chats', 'trades', ['trade_id'], ['trade_id'])
    op.drop_column('chats', 'match_id')
    # ### end Alembic commands ###
